services:
  - type: web
    name: lithos-performance-analytics
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PORT
        value: 5000
